library(covr)
cov <- package_coverage()
print(cov)
zero_coverage(cov)
report(cov, file = file.path("/workdir/tests/coverage-report.html"), browse = FALSE)
codecov(coverage = cov, token = "e8caf097-a857-4abb-94ea-d3d1e51a67cc")
