name: Tests
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    env:
      github_sha: ${{ github.sha }}
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/robinson_code:latest --tag islasgeci/robinson_code:${github_sha:0:4} .
    - name: Verifica el formato
      run: docker run islasgeci/robinson_code:latest make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run islasgeci/robinson_code:latest make coverage
    - name: Docker log-in
      env:
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
      run: echo "${docker_password}" | docker login --username "${docker_username}" --password-stdin
    - name: Upload image to Docker Hub
      run: docker push islasgeci/robinson_code:latest
    - name: Tag image with hash
      run: docker push islasgeci/robinson_code:${github_sha:0:4}
